workspace(name = "validator")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_absl",
    sha256 = "e54f38a7a0d5648d6cb4d8e10b53c9c81f9d337a995524993dd0fcc38f82e608",
    strip_prefix = "abseil-cpp-3132b83a1a1c82df959e000057de27e1b8ff692d",
    urls = ["https://github.com/abseil/abseil-cpp/archive/3132b83a1a1c82df959e000057de27e1b8ff692d.zip"],
)

http_archive(
    name = "com_google_googletest",
    sha256 = "65a34ce622c55e7772bf42c1a10e99215272874d831af291033a02a8cf2bf828",
    strip_prefix = "googletest-a3580180d16923d6d5f488e20b3814608a892f17",
    urls = ["https://github.com/google/googletest/archive/a3580180d16923d6d5f488e20b3814608a892f17.zip"],  # 2019-01-07
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "449a486b00777a078c80815995c821de6b39661530c255a15dff02bcd36bac70",
    strip_prefix = "protobuf-ba348e2b3bf30f3d6f6c356020ac6999ddcf13b0",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/ba348e2b3bf30f3d6f6c356020ac6999ddcf13b0.zip"],
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

http_archive(
    name = "com_github_gflags_gflags",
    sha256 = "017e0a91531bfc45be9eaf07e4d8fed33c488b90b58509dbd2e33a33b2648ae6",
    strip_prefix = "gflags-a738fdf9338412f83ab3f26f31ac11ed3f3ec4bd",
    urls = ["https://github.com/gflags/gflags/archive/a738fdf9338412f83ab3f26f31ac11ed3f3ec4bd.zip"],
)

http_archive(
    name = "com_googlesource_code_re2",
    sha256 = "3664a5d4915f3cf5a9172beb1011dca13d21edc26ce4831a5103140aeae903d2",
    strip_prefix = "re2-c9cba76063cf4235c1a15dd14a24a4ef8d623761",
    urls = ["https://github.com/google/re2/archive/c9cba76063cf4235c1a15dd14a24a4ef8d623761.zip"],
)

# rules_cc defines rules for generating C++ code from Protocol Buffers.
http_archive(
    name = "rules_cc",
    sha256 = "91286857db13f2f7f12242017b9f5714a85038b1df62b926cb75b7610cf40c1b",
    strip_prefix = "rules_cc-7f0992b0bd47d5b24076c2d022ba1819cc8641e4",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/7f0992b0bd47d5b24076c2d022ba1819cc8641e4.zip"],
)
load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies")
rules_cc_dependencies()

# rules_proto defines abstract rules for building Protocol Buffers.
http_archive(
    name = "rules_proto",
    sha256 = "5d4cd6780634eb2ecafa091df8be8009d395f70a02f722e07e063883dd8af861",
    strip_prefix = "rules_proto-493169c1199dc21b9da860f7040a4502aa174676",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/493169c1199dc21b9da860f7040a4502aa174676.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/493169c1199dc21b9da860f7040a4502aa174676.tar.gz",
    ],
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

http_archive(
    name = "emsdk",
    sha256 = "e55704006765ea8e127d76278b1573b114204d19e6972d8a3a2a18f2f2ee4c10",
    strip_prefix = "emsdk-b113f24842c6e97fe3e352084db09a6e278593ae/bazel",
    url = "https://github.com/emscripten-core/emsdk/archive/b113f24842c6e97fe3e352084db09a6e278593ae.tar.gz",
)

load("@emsdk//:deps.bzl", emsdk_deps = "deps")
emsdk_deps()

load("@emsdk//:emscripten_deps.bzl", emsdk_emscripten_deps = "emscripten_deps")
emsdk_emscripten_deps(emscripten_version = "2.0.31")

http_archive(
    name = "com_google_javascript_closure_library",
    sha256 = "f340634ad79e8bd64f5aba626ec0af2769c997b82c59a3b7dc57ac229bdafcba",
    strip_prefix = "closure-library-1763bed09dc1007bf05485f974af12588b4611c9",
    urls = ["https://github.com/google/closure-library/archive/1763bed09dc1007bf05485f974af12588b4611c9.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "861bd3646cf5480c05b0912bf557cb556452672fdf921ad5dbc659c9f814ce11",
    strip_prefix = "rules_closure-3f61bd84ea9b60e65e1a5dbf988608170c4858b7",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/3f61bd84ea9b60e65e1a5dbf988608170c4858b7.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/3f61bd84ea9b60e65e1a5dbf988608170c4858b7.tar.gz",
    ],
)

load("@io_bazel_rules_closure//closure:repositories.bzl", "rules_closure_dependencies", "rules_closure_toolchains")
rules_closure_dependencies()
rules_closure_toolchains()

local_repository(
    name = "amphtml-extensions",
    path = "../extensions",
)
